// frontend/src/components/RankCarousel.tsx
'use client'

import { useState } from 'react'
import Image from 'next/image'

const RANKS = [
    { name: 'Iron', img: '/ranks/iron.png', glow: '#8B7355' },
    { name: 'Bronze', img: '/ranks/bronze.png', glow: '#cd7f32' },
    { name: 'Silver', img: '/ranks/silver.webp', glow: '#90a4ae' },
    { name: 'Gold', img: '/ranks/gold.png', glow: '#FFD700' },
    { name: 'Platinum', img: '/ranks/platinum.png', glow: '#00b4d8' },
    { name: 'Emerald', img: '/ranks/emerald.png', glow: '#3dba6a' },
    { name: 'Diamond', img: '/ranks/diamond.png', glow: '#4a9ee0' },
    { name: 'Master', img: '/ranks/master.png', glow: '#9b59b6' },
    { name: 'Grandmaster', img: '/ranks/grandmaster.png', glow: '#e74c3c' },
    { name: 'Challenger', img: '/ranks/challenger.png', glow: '#ffd600' },
]

const TIERS = ['IV', 'III', 'II', 'I']

export default function RankCarousel() {
    const [current, setCurrent] = useState(0)
    const [tier, setTier] = useState(0)

    const rank = RANKS[current]!

    return (
        <div className="flex flex-col items-center gap-6 py-8">
            {/* Main display */}
            <div
                className="relative w-48 h-48 flex items-center justify-center rounded-full bg-black/30 border border-white/10"
                style={{ boxShadow: `0 0 60px ${rank.glow}55` }}
            >
                <Image
                    src={rank.img}
                    alt={rank.name}
                    width={120}
                    height={120}
                    className="object-contain"
                    style={{ filter: `drop-shadow(0 0 20px ${rank.glow}88)` }}
                />
            </div>

            {/* Rank name */}
            <h3 className="font-serif text-xl font-bold uppercase text-[#fff0f0]">
                {rank.name} {TIERS[tier]}
            </h3>

            {/* Tier selector */}
            <div className="flex gap-2">
                {TIERS.map((t, i) => (
                    <button
                        key={t}
                        onClick={() => setTier(i)}
                        className={`px-3 py-1 rounded-full font-primary text-xs font-bold tracking-wider transition-all duration-200 ${tier === i
                                ? 'bg-red-600 text-white'
                                : 'bg-red-950/40 text-red-400 border border-red-800/30 hover:border-red-600/50'
                            }`}
                    >
                        {t}
                    </button>
                ))}
            </div>

            {/* Navigation */}
            <div className="flex items-center gap-6">
                <button
                    onClick={() => setCurrent((c) => (c - 1 + RANKS.length) % RANKS.length)}
                    className="w-10 h-10 rounded-full bg-red-950/50 border border-red-800/25 flex items-center justify-center text-red-400 hover:border-red-600/50 transition-all duration-200"
                >
                    ←
                </button>
                {/* Dots */}
                <div className="flex gap-1.5">
                    {RANKS.map((_, i) => (
                        <button
                            key={i}
                            onClick={() => setCurrent(i)}
                            className={`rounded-full transition-all duration-200 ${i === current ? 'w-4 h-2 bg-red-500' : 'w-2 h-2 bg-red-800/50'
                                }`}
                        />
                    ))}
                </div>
                <button
                    onClick={() => setCurrent((c) => (c + 1) % RANKS.length)}
                    className="w-10 h-10 rounded-full bg-red-950/50 border border-red-800/25 flex items-center justify-center text-red-400 hover:border-red-600/50 transition-all duration-200"
                >
                    →
                </button>
            </div>
        </div>
    )
}

// src/components/RankCarousel.vue
<script setup lang="ts">
const ROMAN_TIERS = ['IV', 'III', 'II', 'I']

const props = defineProps<{
  ranks: { name: string; img: string; glow: string; hasTiers: boolean }[]
  rankIndex: number
  rankTier: number
  showTiers: boolean
  large?: boolean
}>()

const emit = defineEmits<{
  (e: 'update:rankIndex', value: number): void
  (e: 'update:rankTier', value: number): void
}>()

function prevRank() {
  emit('update:rankIndex', (props.rankIndex - 1 + props.ranks.length) % props.ranks.length)
}
function nextRank() {
  emit('update:rankIndex', (props.rankIndex + 1) % props.ranks.length)
}
</script>

<template>
  <div class="flex items-center gap-3">
    <button
      @click="prevRank"
      class="w-9 h-9 flex items-center justify-center rounded-full border border-violet-700/25 text-violet-700 font-black text-xl transition-colors hover:bg-violet-700/10 shrink-0"
    >
      ‹
    </button>

    <div class="flex-1 flex flex-col items-center gap-3 py-2">
      <!-- Emblema -->
      <div
        :class="`relative select-none ${large ? 'w-36 h-36' : 'w-24 h-24'}`"
        :style="{ filter: `drop-shadow(0 0 ${large ? '22px' : '16px'} ${ranks[rankIndex]!.glow}99)`, transition: 'filter 0.3s ease' }"
      >
        <img
          :key="ranks[rankIndex]!.img"
          :src="ranks[rankIndex]!.img"
          :alt="ranks[rankIndex]!.name"
          class="w-full h-full object-contain"
        />
      </div>

      <!-- Nombre + división -->
      <div class="font-primary font-bold tracking-[2px] text-sm uppercase text-[#0d0820] text-center leading-tight">
        {{ ranks[rankIndex]!.name }}
        <span v-if="showTiers && ranks[rankIndex]!.hasTiers" class="ml-1.5 text-violet-600">
          {{ ROMAN_TIERS[rankTier] }}
        </span>
      </div>

      <!-- Selector de tier -->
      <div v-if="showTiers && ranks[rankIndex]!.hasTiers" class="flex gap-1.5">
        <button
          v-for="(tier, ti) in ROMAN_TIERS"
          :key="tier"
          @click="emit('update:rankTier', ti)"
          :class="`w-9 h-7 font-primary text-[.7rem] font-bold tracking-[1px] transition-all duration-200 border ${ti === rankTier ? 'bg-violet-600 text-white border-violet-600 shadow-[0_0_10px_rgba(124,58,237,.35)]' : 'bg-transparent text-[rgba(30,20,70,.55)] border-violet-700/25 hover:border-violet-600 hover:text-violet-700'}`"
          style="clip-path: polygon(4px 0,100% 0,calc(100% - 4px) 100%,0 100%)"
        >
          {{ tier }}
        </button>
      </div>

      <!-- Dots de posición -->
      <div class="flex gap-1.5 flex-wrap justify-center max-w-[200px]">
        <button
          v-for="(_, i) in ranks"
          :key="i"
          @click="emit('update:rankIndex', i)"
          class="h-1.5 rounded-full transition-all duration-300"
          :style="{ width: i === rankIndex ? '16px' : '6px', background: i === rankIndex ? ranks[rankIndex]!.glow : 'rgba(124,58,237,.22)' }"
        />
      </div>
    </div>

    <button
      @click="nextRank"
      class="w-9 h-9 flex items-center justify-center rounded-full border border-violet-700/25 text-violet-700 font-black text-xl transition-colors hover:bg-violet-700/10 shrink-0"
    >
      ›
    </button>
  </div>
</template>
